spring:
  datasource:
    # MySQL ?? ??
    url: jdbc:mysql://localhost:3306/2024msg?useUnicode=true&characterEncoding=euckr&serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: kingkong
    password: king1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    generate-ddl: true
    show-sql: true # API ?? ? sql?? ??
    hibernate:
      format_sql: true
#      ddl-auto: update
  security:
    user:
      name: user
      password: 1111
  sql:
    init:
      mode: always # 모든 데이터베이스에 sql 스크립트를 동작시킨다

logging:
  level:
    org:
      springframework: debug
      springframework.web: debug